export const REPORT_TYPES = {
    DAILY_FOREX: "ibd-daily_single-currency",
    MONTHLY_BALANCE: "finance-monthly_balance-sheet",
    LIQUIDITY_WEEKLY: "finance-weekly_liquidity",
    LOAN_RELATED_PARTIES: "credit-monthly_loan-related",
    RESERVE_BASE: "finance-monthly_reserve",
    STATUTORY_REQ: "finance-monthly_statutory",
    KEY_BALANCE_SHEET: "finance-monthly_key-balance-sheet",
    CAPITAL_ADEQUACY: "finance-monthly_capital-adequacy",
    DEPOSIT_RANGE_REGION: "finance-monthly_deposit-range-region",
    DEPOSIT_SECTOR_REGION: "finance-monthly_deposit-sector-region",
    LOAN_BREAKDOWN: "credit-monthly_loan-breakdown",
    LOAN_PORTFOLIO: "credit-monthly_loan-portfolio",
    NPL_PROVISIONS: "credit-monthly_loan-nonperforming",
    LOAN_DISBURSEMENT: "credit-monthly_loan-disbursement",
    LOAN_STATUS: "credit-monthly_loan-status",
    LOAN_CLASSIFICATION: "credit-monthly_loan-classification",
    LARGE_BORROWERS: "credit-monthly_large-borrowers",
    LOAN_RANGE_REGION: "credit-monthly_loan-range-region",
    LOAN_SECTOR_REGION: "credit-monthly_loan-sector-region",
    IFB_RANGE_REGION: "ifb-monthly_deposit-range-region",
    IFB_SECTOR_REGION: "ifb-monthly_deposit-sector-region",
    IFB_BALANCE_SHEET: "ifb-monthly_balance-sheet",
    IFB_PROFIT_LOSS: "ifb-monthly_profit-loss",
    IFB_LOAN_RANGE_REGION: "ifb-monthly_loan-range-region",
    IFB_LOAN_SECTOR_REGION: "ifb-monthly_loan-sector-region",
    COLLATERALIZED_PROPERTY_SOLD_LAST18:
        "credit-quarterly_loan-collateralized-properties",
    LOAN_CLASSIFICATION_PROVISIONING: "credit-quarterly_loan-classification",
    NPL_SECTOR_BRANCH: "credit-quarterly_loan-npl-ecosec-branch",
    COLLATERALIZED_PROPERTY_ACQUIRED_LAST18:
        "credit-quarterly_collateralized-property-acquired-last18",
    LOAN_RANGE_REGION_QUARTERLY: "credit-quarterly_loan_range",
    Q_TOP_TWENTY_NPL: "credit-quarterly_loan-nonperforming-top20",
    EXPENSE_BREAKDOWN_QUARTERLY: "finance-quarterly_breakdown-expenses",
    INCOME_ACCOUNT_BREAKDOWN: "finance-quarterly_breakdown-income-account",
    CAPITAL_ADEQUACY_OFFBALANCESHEET: "finance-quarterly_off-balancesheet",
    TOP20_BORROWERS: "credit-quarterly_top20-borrowers",
    BUILDING_CONSTRUCTION: "credit-quarterly_building-construction",
    CONVENTIONAL_LOAN_SECTOR_REGION: "credit-quarterly_loan_sector",
    DEPOSIT_RANGE_REGION_QUARTERLY: "finance-quarterly_deposit-range-region",
    FINANCE_PROFIT_LOSS: 'finance-quarterly_profit-loss',
    CAPITAL_ADEQUACY_ONBALANCESHEET: "finance-quarterly_onbalance-sheet",
    CAPITAL_ADEQUACY_QUARTERLY: "finance-quarterly_capital-adequacy",
    IFB_LOAN_RANGE_REGION_QUARTERLY: "ifb-quarterly_loan-range",
    IFB_LOAN_SECTOR_REGION_QUARTERLY: "ifb-quarterly_loan-sector",
    QUARTERLY_BALANCE_SHEET: "finance-quarterly_balance-sheet",
    QUARTERLY_TOP_TWENTY_DEPOSITORS: "finance-quarterly_top20-depositors",
    QUARTERLY_MATURITY_OF_ASSETS_LIABILITIES: "finance-quarterly_maturity-asset-liability",
    QUARTERLY_MEMORANDUM_AND_CONTINGENT_ACCOUNTS: "finance-quarterly_memorandum",
    IFB_DEPOSIT_RANGE_REGION_QUARTERLY: "ifb-quarterly_deposit-range",
    IFB_DEPOSIT_SECTOR_REGION_QUARTERLY: "ifb-quarterly_deposit-sector",
    QUARTERLY_TOP20_SHAREHOLDERS: 'share-quarterly_top20-shareholders',
    QUARTERLY_TWO_PERCENT_SHAREHOLDERS: 'share-quarterly_top-two-shareholders',
    QUARTERLY_MOBILE_TRANSACTIONS: 'digital-quarterly_mobile-transaction',
    QUARTERLY_ATM_POS: 'digital-quarterly_atm-pos',
    QUARTERLY_TRANSACTION_STATEMENT: 'finance-quarterly_transaction-statement',
    QUARTERLY_RESTRUCTURED_LOANS: 'credit-quarterly_aggregate-restructured-loans',
    QUARTERLY_DIGITAL_LENDING: 'credit-quarterly_digital-lending',
    QUARTERLY_RECATEGORIZED_LOANS: 'credit-quarterly_recategorized-loans',
    QUARTERLY_AGGREGATE_RECATEGORIZED_LOANS: 'credit-quarterly_aggregate-recategorized-loans',
    QUARTERLY_OFF_BALANCE_PROVISIONING: 'credit-quarterly_off-balance-provision',
    QUARTERLY_RESTRUCTURED_ABOVE_5PCT: 'credit-quarterly_restructured-above-5pct',
    MONTHLY_WEIGHTED_AVG_DEPOSIT_RATES: 'finance-monthly_weighted-avg-deposit-rates',
    MONTHLY_IFB_WEIGHTED_AVG_DEPOSIT_RATES: 'ifb-monthly_weighted-avg-deposit-rates',
    MONTHLY_WEIGHTED_AVG_LENDING_RATES: 'credit-monthly_weighted-avg-lending-rates',
    MONTHLY_IFB_WEIGHTED_AVG_LENDING_RATES: 'ifb-monthly_weighted-avg-lending-rates',

};